[package]
name = "binary-blog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
clap = { version = "4.1", features = ["derive", "cargo"] }
hyper = { version = "0.14", features = ["full"] }
pulldown-cmark = "0.9"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
regex = "1"
lazy_static = "1.4"
convert_case = "0.6.0"
