apiVersion: apps/v1
kind: Deployment
metadata:
  name: binary-blog-web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: binary-blog-web
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: binary-blog-web
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: binary-blog-web
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    spec:
      containers:
        - name: binary-blog
          image: astromechza/binary-blog:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--external-url-prefix"
            - {{ if .Values.ingress.tls }}https://{{ else }}http://{{ end }}{{ .Values.ingress.hostname }}
          ports:
            - name: main
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /livez
              port: main
            initialDelaySeconds: 2
            timeoutSeconds: 5
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /readyz
              port: main
            initialDelaySeconds: 2
            timeoutSeconds: 5
            periodSeconds: 2
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 2000
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 125m
              memory: 125M
            limits:
              cpu: 1000m
              memory: 1G
