apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: binary-blog-service-monitor
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: binary-blog-service-monitor
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: binary-blog-service
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: main
      path: /metricz
  targetLabels:
    - app.kubernetes.io/instance
