apiVersion: v1
kind: Service
metadata:
  name: binary-blog-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: binary-blog-service
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  selector:
    app.kubernetes.io/name: binary-blog-web
  ports:
    - name: main
      protocol: TCP
      port: 80
      targetPort: main