name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: paulhatch/semantic-version@v5.0.3
      id: semver
      with:
        tag_prefix: "v"
        bump_each_commit: true
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
    - name: Set crate version
      run: sed -i 's/0.0.0/${{ steps.semver.outputs.version }}/g' Cargo.toml
    - name: Inspect toml
      run: cat Cargo.toml
    - name: Setup Humanitec CLI
      uses: humanitec/setup-cli-action@v1
      with:
        version: "0.21.0"
    - name: Validate score.yaml
      run: humctl score validate score.yaml --org ${{ secrets.HUMANITEC_ORG }} --token ${{ secrets.HUMANITEC_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: docker.io/astromechza/binary-blog:${{ steps.semver.outputs.version }}
    - name: Upload artefact version
      if: github.ref == 'refs/heads/main'
      run: |
        curl https://api.humanitec.io/orgs/${{ secrets.HUMANITEC_ORG }}/artefact-versions \
          -H "Authorization: Bearer ${{ secrets.HUMANITEC_TOKEN }}" \
          -F type=workload -F name=github.com/astromechza/binary-blog \
          -F ref=${{ github.ref }} -F spec=@score.yaml -F commit=${{ github.sha }} \
          -F image=astromechza/binary-blog:${{ steps.semver.outputs.version }}
