name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: paulhatch/semantic-version@v5.0.3
      id: semver
      with:
        tag_prefix: "v"
        bump_each_commit: true
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
    - name: Set crate version
      run: sed -i 's/0.0.0/${{ steps.semver.outputs.version }}/' Cargo.toml
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: docker.io/astromechza/binary-blog:${{ steps.semver.outputs.version }}
    - name: Add version to chart
      run: sed -i 's/X.Y.Z/${{ steps.semver.outputs.version }}/g' chart/Chart.yaml
    - name: Package the chart
      run: tar -czvf binary-blog-${{ steps.semver.outputs.version }}.tgz -C chart .
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.semver.outputs.version_tag }}",
            sha: context.sha
          })
    - name: Release  tag
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.semver.outputs.version_tag }}
        files: |
          binary-blog-${{ steps.semver.outputs.version }}.tgz
          