name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Check version
      run: cargo --version
    - name: Run tests
      run: cargo test --verbose --offline
    - name: Build
      run: cargo build --verbose --release --offline

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - uses: paulhatch/semantic-version@v5.0.2
      id: semver
      with:
        tag_prefix: "v"
        bump_each_commit: true
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: docker.io/astromechza/binary-blog:${{ steps.semver.outputs.version_tag }}
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.semver.outputs.version_tag }}",
            sha: context.sha
          })